### ISSUE TITLE
Service not starting

### ISSUE THREAD

**Issue by metbril** [EBOOZ/TeamsStatus#16]
At first the new script including separate settings didn't work. I tried to run it from the command line and that worked. Then I knew it had to be in installing it as a service.

I have been fiddling to get it working. I'm not sure what finally worked, but I think the install script needs modification. The Settings file also needs to be unblocked, I guess?

This was my install script.

```powershell
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
Unblock-File .\Settings.ps1
Unblock-File .\Get-TeamsStatus.ps1
Start-Process -FilePath .\nssm.exe -ArgumentList 'install "Microsoft Teams Status Monitor" "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" "-command "& { . C:\Scripts\Get-TeamsStatus.ps1 }"" ' -NoNewWindow -Wait
Start-Service -Name "Microsoft Teams Status Monitor"
```

**Comment by EBOOZ** [comment]
I've updated the readme to unblock Settings.ps1 as well in https://github.com/EBOOZ/TeamsStatus/commit/bbcda22f7711fb8a8a49367b34dc47bb15a1c2c6
