### ISSUE TITLE
No need to create input entities first

### ISSUE THREAD

**Issue by metbril** [EBOOZ/TeamsStatus#17]
I purposely didn't create the new input_boolean for the hearbeat before using the new script. It's created by HA with first use. So the instructions can be even simpler.

**Comment by EBOOZ** [comment]
I agree, and the API monitoring doesn't bring what I wanted to achieve. I've removed the binary_sensor in https://github.com/EBOOZ/TeamsStatus/commit/bbcda22f7711fb8a8a49367b34dc47bb15a1c2c6 and updated the readme.
