### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by sanderlv** [EBOOZ/TeamsStatus#19]
Hi, I followed to the letter...

There is an error in the description. Where is says:
`Edit the Get-TeamsStatus.ps1 script` it should say `"Edit the Settings.ps1 script"`

I do get the sensors (homeassistant is not new for me :-))
![image](https://user-images.githubusercontent.com/16528916/109696014-e30f4a00-7b8c-11eb-81c7-ce5f62e092d6.png)

I also added the powershell lines per line (some ask for a Y) in elevated mode... no errors...

But I do not get any update or feedback from teams. I do not know where to look or start to troubleshoot...

Please advise.

**Comment by Sku1ly** [comment]
@sanderlv If you run the script in Powershell you should see an output. I had a typo in my server IP so when I ran it I saw 'Unable to connect to server' (or similar) which led me to checking settings.

**Comment by sanderlv** [comment]
Hi thank you for your time to respond. 

I get:
Error creating service!
CreateService(): The specified service already exists.

But I am sure that I did not have this in the begin... and there is a service running "Microsoft Teams Status Monitor".

**Comment by EBOOZ** [comment]
Hi,

I don't think you need to create the service again (that's why you get the error). Try it this way:
- Download the latest version of Get-TeamsStatus.ps1 script (please note I've removed the API monitoring, so you can remove the binary_sensor teams_monitoring related information from your configuration.yaml)
- Stop the Windows service "Microsoft Teams Status Monitor"
- Start an elevated PowerShell prompt and browse to the folder where the scripts are located
- Run: `Unblock-File .\Settings.ps1` and `Unblock-File .\Get-TeamsStatus.ps1`
- Run: `.\Get-TeamsStatus.ps1` and confirm you don't get any errors and the status is updated in HA
- Press CTRL+C to stop the script and start the Windows Service again

I hope this helps!

**Comment by sanderlv** [comment]
Hi EBOOZ, did exactly as you described... but still no luck...

this error I get:
```
PS C:\windows\system32> cd ..
PS C:\windows> cd ..
PS C:\> cd .\Scripts
PS C:\Scripts> Unblock-File .\Settings.ps1
PS C:\Scripts> Unblock-File .\Get-TeamsStatus.ps1
PS C:\Scripts> .\Get-TeamsStatus.ps1
Available
Invoke-RestMethod : 404: Not Found
At C:\Scripts\Get-TeamsStatus.ps1:166 char:5
+     Invoke-RestMethod -Uri "$HAUrl/api/states/$entityStatus" -Method POST -Heade ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invoke-RestMethod : 404: Not Found
At C:\Scripts\Get-TeamsStatus.ps1:180 char:5
+     Invoke-RestMethod -Uri "$HAUrl/api/states/$entityActivity" -Method POST -Hea ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Available
Available
Available
Available
Available
Available
Available
Available
```

And with regards to "(please note I've removed the API monitoring, so you can remove the binary_sensor teams_monitoring related information from your configuration.yaml)" Is do now miss 1 entity, that's the right one correct?
![image](https://user-images.githubusercontent.com/16528916/110301728-b332cd00-7ff8-11eb-96fe-fd67cea6d791.png)

**Comment by sanderlv** [comment]
Is it possible to get some help I would really like this to work :-)

**Comment by EBOOZ** [comment]
It looks like your HA URL is incorrect:
![image](https://user-images.githubusercontent.com/16918535/111446764-07326580-870d-11eb-9dcf-5de0020303ff.png)

**Comment by sanderlv** [comment]
Hi, that can't be, it is an ip address only...

$HAUrl = "http://192.168.1.142"

Not sure but it should not be like:

$HAUrl = "http://192.168.1.142:8123"???

EDIT:
Yes! please update the documentation to clearly point out it uses 8123 port!

**Comment by EBOOZ** [comment]
Not everybody is using port 8123 :)

**Comment by sanderlv** [comment]
I think 99.9% does indeed :-)
