### ISSUE TITLE
Issue with creating sensors - log attached

### ISSUE THREAD

**Issue by Thrasher2020** [EBOOZ/TeamsStatus#2]
Logger: homeassistant.components.template.template_entity
Source: components/template/template_entity.py:239
Integration: template (documentation, issues)
First occurred: 16:28:04 (2 occurrences)
Last logged: 16:28:04

Template loop detected while processing event: <Event state_changed[L]: entity_id=sensor.teams_activity, old_state=<state sensor.teams_activity=Offline; friendly_name=Microsoft Teams activity, icon=mdi:microsoft-teams @ 2021-01-12T16:28:03.880826+00:00>, new_state=<state sensor.teams_activity=; friendly_name=Microsoft Teams activity, icon= @ 2021-01-12T16:28:04.149008+00:00>>, skipping template render for Template[{% if states('sensor.teams_activity') == '' -%} Offline {%- endif %}]
Template loop detected while processing event: <Event state_changed[L]: entity_id=sensor.teams_activity, old_state=<state sensor.teams_activity=Offline; friendly_name=Microsoft Teams activity, icon=mdi:microsoft-teams @ 2021-01-12T16:28:03.880826+00:00>, new_state=<state sensor.teams_activity=; friendly_name=Microsoft Teams activity, icon= @ 2021-01-12T16:28:04.149008+00:00>>, skipping template render for Template[{% if states('sensor.teams_activity') == '' -%} mdi:microsoft-teams {%- endif %}]

**Comment by EBOOZ** [comment]
This is a known bug indeed. I didn't find the time yet to get this resolved. It's on my to-do list, but has less priority ;)

The sensors will be created though, and will be updated sucessfully.

**Comment by metbril** [comment]
https://community.home-assistant.io/t/template-loop-detection-broke-my-cover-template/231525

**Comment by metbril** [comment]
~~For now I have settled with this configuration, that seems to be working just fine. By adding the fixed value of `unknown`, the sensors will NOT be updated automatically. Just what we want.~~

That didn't work after all.

```yaml
# DELETED SAMPLE
```

I have settled with `input_text` entities; see my config repo:

https://github.com/metbril/home-assistant-config/blob/main/packages/presence/msteams.yaml

**Comment by EBOOZ** [comment]
That's a nice workaround :) I'll test it out and update the documentation when things work out.

**Comment by EBOOZ** [comment]
Works like a charm! I've updated the ReadMe in commit https://github.com/EBOOZ/TeamsStatus/commit/33127d6cb30765edbbcac3f015d977df3c374c7d

**Comment by metbril** [comment]
You should've  also changed the default sensor names in the settings script.
