### ISSUE TITLE
(UFT8) Same issue in latest version.

### ISSUE THREAD

**Issue by ValleBL** [EBOOZ/TeamsStatus#24]
Same issue in latest version.
I changed the settings.ps1 encoding to "UFT8 with BOM" and now its working!
Maybe you could change this in master.

_Originally posted by @ValleBL in https://github.com/EBOOZ/TeamsStatus/issues/7#issuecomment-800421222_

**Comment by EBOOZ** [comment]
Wat did you change, exactly?

**Comment by ValleBL** [comment]
I changed the whole file encoding to UTF with BOM with VSCode.
Changing it back broke the UFT 8 encoding too. So this might be the solution. At least for me
