### ISSUE TITLE
Status does not update when call is finished

### ISSUE THREAD

**Issue by dinki** [EBOOZ/TeamsStatus#29]
I’ve been using this for about a month and it works well, but I am getting an issue where my status is not going back to ‘Not in a call’ when I close out a call. I have to kill Teams and reopen it to get things synced again. 

Has anyone run into this?  Any ideas on troubleshooting?  It does not happen every time but it does happen fairly often (at least once per day).

**Comment by EBOOZ** [comment]
I've seen this happening because of the increased logging of the client. Have you picked or noticed the increased amount of lines that is being gathered by the script?

**Comment by dinki** [comment]
@EBOOZ Apologies for this, but can you tell me where to find the logging you're mentioning?

**Comment by EBOOZ** [comment]
This is the code in the script: 
`$TeamsStatus = Get-Content -Path "C:\Users\$UserName\AppData\Roaming\Microsoft\Teams\logs.txt" -Tail 1000 | Select-String -Pattern `
  'Setting the taskbar overlay icon -',`
  'StatusIndicatorStateService: Added' | Select-Object -Last 1`

Get-Content searches in the logs.txt file for certain phrases. It tails the logfile for the last 1000 lines (in the latest version of the script).

**Comment by dinki** [comment]
Thanks for the speedy response.  I'll give it a look.  

I may also need to update the script. Is that a matter of just updating the code in c:\scripts and rebooting?

**Comment by EBOOZ** [comment]
If you are already using the separated Settings.ps1 file, then it's just replacing the Get-TeamsStatus.ps1 script. Otherwise you'll need to copy/past the information from your old Get-TeamsStatus.ps1 version to Settings.ps1, and then use the latest version.

**Comment by pswarts** [comment]
I had the same issue. I increased the tail size to 10000 and the problem went away

**Comment by dinki** [comment]
@pswarts  Thanks for posting this.  I've made the change and so far the problem has gone away for me as well.

@EBOOZ I'm not sure of the mechanism, but perhaps this could be explored for the sake of others using your script?

Thanks to you both!

**Comment by metbril** [comment]
Is this fixed with #36 or #38?

**Comment by EBOOZ** [comment]
I finally got some spare time to update the script to work with the new client, so please download the latest version and try again.
