### ISSUE TITLE
Status Not updating

### ISSUE THREAD

**Issue by jimmyeao** [EBOOZ/TeamsStatus#30]
This was working fine, however after a rebuild and reinstall of my PC, the service isn't working - runs fine if I run the script manually. Is there any logging?

**Comment by jimmyeao** [comment]
I should add, the service is running, just doesn't appear to do anything

**Comment by ImaBadCoder** [comment]
I added logging and found that it wasn't looking in the correct place for the log file. Was trying to read a file in the Win32 directory. I went back to hard coding the log location and that fixed the issue.

**Comment by jimmyeao** [comment]
Confirmed working, thanks!

**Comment by m-a-johnson** [comment]
Can you advise how you fixed where the log file is? I think I may be having the same issue.

**Comment by jimmyeao** [comment]
look in the script for lines 51 and 56:
![image](https://user-images.githubusercontent.com/5197831/117261235-d7b7f380-ae47-11eb-858b-b174d63d86ef.png)
instead of` $env:APPDATA"\Microsoft\Teams\logs.txt"` put the full path, e.g.
`"c:\users\yourusername\appdata\roaming\Microsoft\Teams\logs.txt"`

**Comment by m-a-johnson** [comment]
Awesome! That worked. I made that change and then had to do a restart, but it seems to be updating! Thank you for the help.

**Comment by vujins** [comment]
Worked for me too, thanks!
