### ISSUE TITLE
Service doesn't update status when using Env:AppData

### ISSUE THREAD

**Issue by bmdixon** [EBOOZ/TeamsStatus#33]
The change made in [this commit](https://github.com/EBOOZ/TeamsStatus/commit/d100c67b346dd78c0cecb3a48ccabb2325e8be62) break the service unless it is running under your actual user account. By default the service runs as `LocalSystem` so cannot find the teams log file.

Reverting this change fixed the service for me.

**Comment by guyke01** [comment]
I had the same problem after i changed the script with the commit. After i changed the service to log on as my own user instead of Local System it worked again. If the script is running under your own user it can read the $env:APPDATA variable.

**Comment by jimmyeao** [comment]
This no longer works for me when running as a service, either under the system account, or my own account.
Instead, I have set to run as a schedule task:
![image](https://user-images.githubusercontent.com/5197831/118672074-e01d1080-b7ef-11eb-973c-6fe2eb9daae5.png)
![image](https://user-images.githubusercontent.com/5197831/118672105-e57a5b00-b7ef-11eb-9ff9-eea37ee5b53c.png)
![image](https://user-images.githubusercontent.com/5197831/118672135-ed39ff80-b7ef-11eb-927d-8e46075fb294.png)
and for those of you that leave your computer on 24/7, untick the "Stop task if it runs longer than"
![image](https://user-images.githubusercontent.com/5197831/118672287-080c7400-b7f0-11eb-9620-a108c94aee75.png)

**Comment by EBOOZ** [comment]
It requires some additional work when setting the script up, but I'd advise to use the $LocalUsername variable in `Settings.ps1` to work around this.
