### ISSUE TITLE
Status entity no longer updating

### ISSUE THREAD

**Issue by Nuuki9** [EBOOZ/TeamsStatus#35]
I've been using the script for months without any issues - I run it as a Scheduled Task at login, and by combining it with my calendar data its been great to let my kids know when I'm free, on a sensitive "do not disturb" call, or when I'm on a call with my team which they can disturb if they want to say hello.

Recently however, I'm finding that the `Activity` entity isn't updating correctly. If I start and drop calls the `Status` entity correctly changes, but `Activity` remains stuck on _In a call_.

For now I've updated my NodeRed flows to trigger off `Activity`, and that's fine, but I as you get useful information through `Status` it would be ideal to resolve that at some point.

**Comment by ImaBadCoder** [comment]
I had the same issue. I updated the script to look at the last 2000 lines, it fixed the issue. So, to clarify, 

Change $TeamsStatus = Get-Content -Path $env:APPDATA"\Microsoft\Teams\logs.txt" -Tail 1000 | Select-String -Pattern `

to 

$TeamsStatus = Get-Content -Path $env:APPDATA"\Microsoft\Teams\logs.txt" -Tail 2000 | Select-String -Pattern `

**Comment by ImaBadCoder** [comment]
To clarify, there are 2 lines that look similar. I updated both.

**Comment by Nuuki9** [comment]
Many thanks - I've updated both settings and it looks to be responding better, though I'll continue to keep an eye on it.
