### ISSUE TITLE
Status is always unknown

### ISSUE THREAD

**Issue by bluckau** [EBOOZ/TeamsStatus#37]
Hi, very excited about this method of updating Teams status. However, the status is always showing as unknown. Is there a log I can look at or another way to tell what it is doing?

Does this work with NabuCasa? 
![chrome_Aa0YY7amrh](https://user-images.githubusercontent.com/7170629/126811161-41006da5-073c-4e50-9674-67324b11c2fc.png)

**Comment by bluckau** [comment]
I rebooted and now the status is always offline. I noticed this if I run the powershell myself, every time the status changes:

Invoke-RestMethod : 404: Not Found
At C:\scripts\Get-TeamsStatus.ps1:164 char:5
+     Invoke-RestMethod -Uri "$HAUrl/api/states/$entityStatus" -Method  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by ImaBadCoder** [comment]
Check your Home Assistant URL in the Settings.ps1 file. Can you access that URL outside of the script?

**Comment by OCNice** [comment]
Similar issue here, but I get a 401 error.. 
`Invoke-RestMethod : 401: Unauthorized
At C:\Scripts\TeamsStatus-main\Get-TeamsStatus.ps1:164 char:5
+     Invoke-RestMethod -Uri "$HAUrl/api/states/$entityStatus" -Method  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand`

**Comment by umutcelebi** [comment]
Same issue here.

Anyone managed to fix this?

**Comment by EBOOZ** [comment]
I finally got some spare time to update the script to work with the new client, so please download the latest version and try again.
