### ISSUE TITLE
UTF8-Issue when reading Teams\log.txt

### ISSUE THREAD

**Issue by okrasa** [EBOOZ/TeamsStatus#43]
When reading the logs.txt to get the $TeamsStatus variable an error may occur when the OS uses a different language that includes umlauts, for example

```
Mit Jan 19 2022 19:33:51 GMT+0100 (MitteleuropÃ¤ische Normalzeit) <5284> -- info -- Setting the taskbar overlay icon - 
             VerfÃ¼gbar 
```

Can be fixed by adding `-Encoding Utf8` to the` $TeamsStatus = Get-Content` call.

**Comment by EBOOZ** [comment]
This is fixed in the latest version
