### ISSUE TITLE
Teams Monitoring Computer Binary_Sensor

### ISSUE THREAD

**Issue by ImaBadCoder** [EBOOZ/TeamsStatus#45]
I see that the settings file has the following entries, but the get-teamstatus.ps1 is not doing anything with those as well as the binary_sensors aren't created. 

$entityHeartbeat = "binary_sensor.teams_monitoring_computer"
$entityHeartbeatName = "Microsoft Teams monitoring Computer"

Is there more to the script that can be added?

thanks

**Comment by EBOOZ** [comment]
I've removed this for now in the updated script, because it wasn't used. I finally got some spare time to update the script to work with the new client, so please download the latest version and try again.
