### ISSUE TITLE
The new Teams does not write to the same log file.

### ISSUE THREAD

**Issue by Romanmir** [EBOOZ/TeamsStatus#46]
I had the opportunity to update to the New Teams experience and found that it doesn't write to the same log file that the old version does. I'm not sure if this is intended or not, but people using the New Teams experience should probably be aware that, unless something changes, this will break this powershell script.

**Comment by AntoineGS** [comment]
I have posted an updated version of this project here before but I have a new application that handles the new Teams using the WebSockets API. Their API does not have as many data points but it works well (it does HA and MQTT)!
https://github.com/AntoineGS/teams-status-rs

If ever you (or anyone reading this) finds a way of getting the Powershell script working with the New Teams I would be happy to integrate it here: https://github.com/AntoineGS/TeamsStatusV2

**Comment by latetedemelon** [comment]
@AntoineGS @EBOOZ - New teams is now writing updates to a log file located here which might be able to be used:

C:\Users\username\AppData\Local\Packages\MSTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\Logs

**Comment by AntoineGS** [comment]
Hi! I am currently on working on extending my current integration project with that file for more data points, though it is moving slowly: https://github.com/AntoineGS/teams-status-rs/issues/7

**Comment by latetedemelon** [comment]
Awesome.  I’m constrained on my side so I need a non-elevated Power script
only solution.  My workstation whitelists exe files

**Comment by AntoineGS** [comment]
So they do not allow running any non-approved exes? That sucks :(
I am not actively making changes to the Powershell version but if there is a PR I will definitely review and merge it.

**Comment by latetedemelon** [comment]
FYI for those following, I've added a WIP PR that adds support for the new log file.

**Comment by EBOOZ** [comment]
I finally got some spare time to update the script. Thanks to @latetedemelon & @AntoineGS who I borrowed some code from 😊. Please download the latest version and try again.
