### ISSUE TITLE
Cannot get it to report status til HA- sensors

### ISSUE THREAD

**Issue by Hoekeren** [EBOOZ/TeamsStatus#5]
I have succesfulle created the sensors in HA, but they don not update. 

Must have done something wrong i the instalation proces on my pc. 

Created longl-life token and copied it into the program (Does the " have to stay or go) I have left the out.
Regardng the user. It it not clear to me whether it is the "user" on PC with is "XXX" or the user in teams "XXX@compani.org" 
I asume it is the later and have again left out the" The descriptons in the Get-TeamsStatus.ps1 and the Readme.md are not alike on this mater.

Url : Can I use my local IP-adress or do i need to use my HTTP://bussemand.duckdns.org:8123
Ran the PowerShellcommands - no errors

I realised that i had made a typeo in my first atempt after having run the powershel commands - went back and corrected the typeo and ran the powershell commands again. this time getting the error that the service already excists.

I hope yoe are able and willing to help me.

Kind regards 

Christian

**Comment by EBOOZ** [comment]
Hi Christian,

Here's my config:
![image](https://user-images.githubusercontent.com/16918535/104658730-b8902d00-56c3-11eb-8186-0b4322bdb6d1.png)

To answer your questions:
- The " needs to stay for every variable
- The path is where the logs.txt file is located. This is usually C:\Users\XXX\AppData\Roaming\Microsoft\Teams\logs.txt. You can look up the logged in username when you open a command prompt (cmd.exe) and run: echo %USERNAME%
- You can also try to run the script interactive. Open up a PowerShell prompt (powershell.exe), browse to the script folder location and run it via:
![image](https://user-images.githubusercontent.com/16918535/104659153-72879900-56c4-11eb-803d-43801eae9854.png)
- To confirm you can reach the API url, you can try to start a browser and browse to the api URL. This first part is the same that you use when you browse to the Lovelace interface http(s)://yourhaurl/api/states/sensor.teams_status. You should see a 401: Unauthorized error. Please don't forget to specify the port (80, 443 or 8123).

Hopefully you can get it to work!

**Comment by EBOOZ** [comment]
Closing this issue. Feel free to reopen if things don't work out.
