### ISSUE TITLE
Service Fails to start

### ISSUE THREAD

**Issue by Sku1ly** [EBOOZ/TeamsStatus#6]
Hi,

I'm having issues starting the service, it immediately goes into a pause state. There are no error messages attached to the event viewer logs.

I'm using a Microsoft account as my login, W10 Pro 2004

PS error is this

```
Start-Service : Failed to start service 'Microsoft Teams Status Monitor (Microsoft Teams Status Monitor)'.
At line:1 char:1
+ Start-Service -Name "Microsoft Teams Status Monitor"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand
```

Thanks

**Comment by Sku1ly** [comment]
Figured it out - running scripts was disabled but it didn't give me this error when running the start-process bit.

It showed up once I tried the script manually.

**Comment by EBOOZ** [comment]
I've updated the PowerShell instructions to have this issue resolved upfront. Thanks for noticing!
