### ISSUE TITLE
UTF Encoding for JSON

### ISSUE THREAD

**Issue by ValleBL** [EBOOZ/TeamsStatus#7]
First of all i want to thank you for this great integration!

I found a "bug" while sending the command when there is a "ä, ü, ö," etc. in the set language block.
Is there anything i can do to solve this?
Works just fine then i send "Verfuegbar" for example

```
Invoke-RestMethod : {"message": "Invalid JSON specified."}
In C:\Scripts\Get-TeamsStatus.ps1:162 Zeichen:5
+     Invoke-RestMethod -Uri "$HAUrl/api/states/sensor.teams_status" -M ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

**Comment by EBOOZ** [comment]
Thanks for bringing this in. I'll have a look asap.

**Comment by ValleBL** [comment]
Added UTF8 encoding in latest pull request

**Comment by ValleBL** [comment]
Same issue in latest version.
I changed the settings.ps1 encoding to "UFT8 with BOM" and now its working!
Maybe you could change this in master.
